apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx  # لازم الاسم ده يطابق الـ label اللي في الـ Deployment بتاعك
  ports:
    - protocol: TCP
      port: 80          # البورت اللي الناس هتفتح عليه الموقع
      targetPort: 80    # البورت اللي الـ Nginx شغال عليه جوه الـ Container